# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build tools

on:
  push:
    branches:
    - master

    # This specifically builds only the tool projects.
    # Everything else can be ignored.
    paths:
      - '.github/workflows/build_tools.yml'
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'ItemEditor/**'
      - 'N3CE/**'
      - 'N3FXE/**'
      - 'N3ME/**'
      - 'N3TexViewer/**'
      - 'N3Viewer/**'
      - 'SkyViewer/**'
      - 'TblEditor/**'
      - 'UIE/**'
      - 'Server/shared/**'
      - 'Client/N3Base/**'
      - 'Tools.sln'
      - 'ThirdParty.sln'

  pull_request:
    branches:
    - master

    # This specifically builds only the tool projects.
    # Everything else can be ignored.
    paths:
      - '.github/workflows/build_tools.yml'
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'ItemEditor/**'
      - 'N3CE/**'
      - 'N3FXE/**'
      - 'N3ME/**'
      - 'N3TexViewer/**'
      - 'N3Viewer/**'
      - 'SkyViewer/**'
      - 'TblEditor/**'
      - 'UIE/**'
      - 'Server/shared/**'
      - 'Client/N3Base/**'
      - 'Tools.sln'
      - 'ThirdParty.sln'
 
  merge_group: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM: [Win32]

    name: "Tools: ${{ matrix.BUILD_CONFIGURATION }} - ${{ matrix.BUILD_PLATFORM }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build tools
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" Tools.sln
