# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build client

on:
  push:
    branches:
    - master

    # This specifically builds only the client (KnightOnline.exe) project.
    # Everything else can be ignored.
    paths:
      - '.github/workflows/build_client.yml'
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'deps/libjpeg-turbo/**'
      - 'deps/libjpeg-turbo-msvc/**'
      - 'Client/JpegFile/**'
      - 'Client/N3Base/**'
      - 'Client/WarFare/**'
      - 'Server/shared/**'
      - 'Client.sln'

  pull_request:
    branches:
    - master

    # This specifically builds only the client (KnightOnline.exe) project.
    # Everything else can be ignored.
    paths:
      - '.github/workflows/build_client.yml'
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'deps/libjpeg-turbo/**'
      - 'deps/libjpeg-turbo-msvc/**'
      - 'Client/JpegFile/**'
      - 'Client/N3Base/**'
      - 'Client/WarFare/**'
      - 'Server/shared/**'
      - 'Client.sln'
 
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM: [Win32]

    name: "Client: ${{ matrix.BUILD_CONFIGURATION }} - ${{ matrix.BUILD_PLATFORM }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build client
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" /p:NO_CLIENT_ASSETS="1" Client.sln
