# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build server

on:
  push:
    branches:
    - master

    # This specifically builds only the server projects.
    # Everything else can be ignored.
    paths:
      - '.github/workflows/build_server.yml'
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'deps/ZipArchive/**'
      - 'deps/zlib/**'
      - 'deps/zlib-msvc/**'
      - 'Server/AIServer/**'
      - 'Server/Aujard/**'
      - 'Server/Ebenezer/**'
      - 'Server/ItemManager/**'
      - 'Server/shared/**'
      - 'Server/VersionManager/**'
      - 'Client/N3Base/My_3DStruct.h'
      - 'Client/N3Base/N3ShapeMgr.h'
      - 'Client/N3Base/N3ShapeMgr.cpp'
      - 'Server.sln'
      - 'ThirdParty.sln'

  pull_request:
    branches:
    - master

    # This specifically builds only the server projects.
    # Everything else can be ignored.
    paths:
      - '.github/workflows/build_server.yml'
      - 'props/**'
      - 'deps/dx9sdk/**'
      - 'deps/ZipArchive/**'
      - 'deps/zlib/**'
      - 'deps/zlib-msvc/**'
      - 'Server/AIServer/**'
      - 'Server/Aujard/**'
      - 'Server/Ebenezer/**'
      - 'Server/ItemManager/**'
      - 'Server/shared/**'
      - 'Server/VersionManager/**'
      - 'Client/N3Base/My_3DStruct.h'
      - 'Client/N3Base/N3ShapeMgr.h'
      - 'Client/N3Base/N3ShapeMgr.cpp'
      - 'Server.sln'
      - 'ThirdParty.sln'
 
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM: [Win32]

    name: "Server: ${{ matrix.BUILD_CONFIGURATION }} - ${{ matrix.BUILD_PLATFORM }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build server
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" Server.sln
